[paths]
enabled = "local"

[paths.local]
train = "data/train.parquet"
test = "data/test.parquet"
sample = "data/sample_submission.csv"
cache = "data/cache.pickle"

[paths.kaggle]
train = "/kaggle/input/wsdm-cup-multilingual-chatbot-arena/train.parquet"
test = "/kaggle/input/wsdm-cup-multilingual-chatbot-arena/test.parquet"
sample = "/kaggle/input/wsdm-cup-multilingual-chatbot-arena/sample_submission.csv"